28 diet
spbu-math-cs/zakroma pull request #32
Opened 2024-05-06 22:20 UTC by arnyyyyy

Посмотрите, пожалуйста, на соответствие требованиям. Если все ок, то адаптирую под обновленный код из main

2024-05-09 01:31 UTC, roscherk requested changes

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                child: ListView.builder(
У нас под нужды списков с рамочками есть класс `FlatList`

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                child: ListView.builder(
Если присмотреться (или открыть Inspector), то можно заметить, что у ListView есть свой небольшой padding сверху, причём его не убрать даже выставлением поля padding в ноль))0)
Как пофиксить: использовать FlatList (рекомендуется) или писать [такое](https://stackoverflow.com/questions/67310122/flutter-how-to-remove-empty-space-at-the-top-of-listview).

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                        leadingDistribution: TextLeadingDistribution.proportional,
А что делает эта штука? Вопрос без подхвоха, я просто ряльно в первый раз вижу))

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                      height: double.infinity,
А зачем, без этого что-то ломается? Я вроде закомментил и у меня выглядит так же

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                            Icons.add_circle_outline,
```suggestion
                                      child: IconButton(
                                          icon: const Icon(
                                            Icons.add_circle_outline,
```
Кесарю кесарево, иконкам IconButton

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                            color: Colors.black,
За цветами бегаем в константы
```suggestion
                                            color: Theme.of(context)
                                                .colorScheme
                                                .onPrimaryContainer,
```
правда, придётся const у кнопки убрать, это да

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                              right: constants.paddingUnit),
В точности
```suggestion
                                          padding: constants.dTextPadding
```

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                  runSpacing: -constants.paddingUnit,
Если закинуть в стиль `ElevatedButton` ещё строчку `tapTargetSize: MaterialTapTargetSize.shrinkWrap`, то противный стандартный паддинг у кнопки уберётся и можно будет написать православное 
```suggestion
                                  runSpacing: constants.paddingUnit / 2
```

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                                  : buttonFamilyRatio,
Надо закинуть цвет в темку в theme.dart

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                              onTap: () {},
По идее, тут надо делать то же самое, что и в trailing кнопке, однако если потыкать, то заметно, что заливка не стыкуется с рамкой, поэтому лучше убрать

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                      style: ElevatedButton.styleFrom(
В фигме явно нарисовано с `elevation: 0`, но здесь, если добавить, почему-то ломается цвет у семейных приёмов

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +        title: const Text('Введите название рациона'),
Таки приёма пищи

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +      return AlertDialog(
У нас есть готовое такое — глянь `alert_text_prompt.dart`

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +              gagList[indexDay].soloRatio.add(inputText);
Я помню, ты говорила, что добавленный приём не сразу отображается на экране — чтобы сразу перерисовывалось, надо переделать `DietListPage` в `ConsumerStatefulWidget` и тут фигачить `setState`

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                    right: 0),
Почему `right: 0`?
```suggestion
                padding: EdgeInsets.all(constants.paddingUnit * 2),
```

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                            // TODO: что здесь ожидается?
Экран 90 в фигме

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                      gagList[index].soloRatio.isEmpty
Если они оба пусты, то мы на этот экран попасть никак не можем (по крайней мере, в текущей реализации)

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                      itemExtent: constants.paddingUnit / 2.5 * gagDishList.length,
Если блюд меньше 7, начинаются проблемы с отображением(

2024-05-09 01:31 UTC, roscherk commented on lib/pages/diets_page.dart
> +                                      itemCount: gagDishList.length,
Мы тут хотим показывать 3 первых блюда, а остальное сворачивать (см. экран 101)

2024-05-19 21:18 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                        leadingDistribution: TextLeadingDistribution.proportional,
Я это скопировала с того, как отображаются даты в home_page (139 строка)

2024-05-19 21:21 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                      height: double.infinity,
У меня иначе странно отображалась кнопка

2024-05-19 21:44 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                  runSpacing: -constants.paddingUnit,
оо, круто, спасибо!

2024-05-20 18:01 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                      itemCount: gagDishList.length,
Не знаю, мне кажется не очень, что придется три раза нажимать (Питание -> день -> прием пищи), чтобы увидеть все блюда

2024-05-20 18:01 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                      itemExtent: constants.paddingUnit / 2.5 * gagDishList.length,
пофиксила

2024-05-20 18:02 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                              onTap: () {},
вот тут не поняла, что имеется в виду, закомментила 91-ю строчку

2024-05-20 18:04 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +                                      style: ElevatedButton.styleFrom(
Там была бага в цвете (;﹏;) Починила, сейчас должно работать

2024-05-20 18:05 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +        title: const Text('Введите название рациона'),
А в 215-ой строчке оставить "рацион"?

2024-05-20 18:17 UTC, arnyyyyy commented on lib/pages/diets_page.dart
> +              gagList[indexDay].soloRatio.add(inputText);
Я правильно понимаю, что в таком случае мне нужно перенести gagList в класс DietListPage? Просто в таком случае мои другие окна (добавления приема пищи и со списком блюд) не имеют к нему доступ

2024-05-23 22:10 UTC, DmGvozd requested changes
Оч круто выглядит, но после перехода в день недели у меня начинается какая-то недопонимашка(
1. Мы не хотим показывать более 3 блюд в приеме пищи (блюд в приеме больше, снизу появляется строка "и еще X", где Х - количество спрятанных в преме блюд, помимо тех, что уже отображены)
2. на этом же экране листать в приемах список блюд мы также не хотим (из-за этого появляется очень неприятный баг, когда хочется пролистать приемы вниз до конца, а листаются блюда в одном из приемов. нужно целиться пальцем в правую часть экрана со стрелочками)
3. переход в информацию о приеме хотим осуществлять при нажатии на все окно приема (с названием, списком блюд в этом приеме и стрелочкой), а не только при нажатии на стрелочку
4. баг с отсутствием навигационной панели фиксится, думаю, довольно быстро (это просто чтобы не забыть, но по факту мы еще будем думать на тем, как лучше обыграть переход от экрана к экрану в этом разделе)
4*. думаю, все же навигационную панель сюда допилить нужно

2024-05-26 07:58 UTC, arnyyyyy commented
Исправила замечания, кроме 4* : пока не знаю, как допилить навигационную панель, так как она лежит в main'е в виджете-родителе, и там трудности с извлечением виджетов, в которые нужно переходить в навигационной панели

2024-05-27 21:04 UTC, closed without merging