Update user.dart and settings_page.dart.
spbu-math-cs/zakroma pull request #39
Opened 2024-05-11 13:36 UTC by DmGvozd

2024-05-11 13:40 UTC, DmGvozd commented
Если фамилия не отображается, значит имя слишком длинное

2024-05-11 13:50 UTC, DmGvozd commented
При вводе слишком большого имени возникает ошибка. Длину имени нужно ограничить, а кнопку выхода из аккаунта переместить. Всем этим буду заниматься уже в другом issue, посвященном странице профиля.

2024-05-11 13:53 UTC, DmGvozd commented
временно сократил длину отображаемого имени, чтобы не возникала ошибка

2024-05-11 16:40 UTC, roscherk requested changes

2024-05-11 16:40 UTC, roscherk commented on lib/data_cls/user.dart
> +        (jsonDecode(responseName.body) as Map<String, dynamic>).values.toList();
1. Когда пишешь `final`, тип дополнительно указывать не нужно, то есть можно было просто `final nameList`
2. Лучше обрабатывать json'ы по аналогии с body сверху:
```suggestion
    final nameBody = jsonDecode(response.body) as Map<String, dynamic>;
```
и дальше `nameBody['name']` вместо `nameList[0]`.
Так лучше, потому что
1. Лучше читается: глядя на  `nameBody['name']` сразу понятно, что мы достаём из словаря имя
2. Сообщения об ошибках более информативны: если, например, фамилия нам не придёт, то в случае с `nameList` мы получим непонятную ошибку про index out of bounds в массиве, а в случае с `nameBody` — более наглядную ошибку о том, что в словаре не нашлось ключа `name`
3. Исключает случаи, когда нам в ответ прислали какой-то мусорный json типа
```json
{
  "trashKey1": 123,
  "trashKey2": 0.42
}
```
а мы считали только ключи (`.values`) и скушали.

2024-05-11 16:40 UTC, roscherk commented on lib/pages/main/4_profile_page.dart
> +                                      overflow: TextOverflow.ellipsis,
`overflow` равен этому по умолчанию — глянь реализацию `StyledHeadline` :)
Поэтому, уточнять это нужно не здесь, а в предыдущем хэдлайне, если ты хочешь у него другое поведение при overflow

2024-05-11 16:40 UTC, roscherk commented on lib/data_cls/user.dart
> +    }
Вместо запроса, а после него `switch` с обработкой статусов, лучше использовать `processResponse` — глянь пример в `diet.dart` строки 72-74

2024-05-16 19:51 UTC, roscherk requested changes

2024-05-16 19:51 UTC, roscherk commented on lib/data_cls/user.dart
> +    final nameBody = (jsonDecode(responseName.body) as Map<String, dynamic>);
```suggestion
    final nameBody = processResponse(await ref.watch(clientProvider).get(
        makeUri('api/user/name'),
        headers: makeHeader(
            body['token'],
            cookies
                .firstWhere((element) => element.key == 'zakroma_session')
                .value)));
```

2024-05-16 20:00 UTC, roscherk approved these changes

2024-05-16 20:00 UTC, merged